var annotated_dup =
[
    [ "ACC_AXES_READING_T", "struct_a_c_c___a_x_e_s___r_e_a_d_i_n_g___t.html", "struct_a_c_c___a_x_e_s___r_e_a_d_i_n_g___t" ],
    [ "ACC_RANGE_SET_T", "struct_a_c_c___r_a_n_g_e___s_e_t___t.html", "struct_a_c_c___r_a_n_g_e___s_e_t___t" ],
    [ "ACC_READING_T", "struct_a_c_c___r_e_a_d_i_n_g___t.html", "struct_a_c_c___r_e_a_d_i_n_g___t" ],
    [ "ADV_SWITCH_ENABLED_T", "struct_a_d_v___s_w_i_t_c_h___e_n_a_b_l_e_d___t.html", "struct_a_d_v___s_w_i_t_c_h___e_n_a_b_l_e_d___t" ],
    [ "ANCS_GET_NTF_T", "struct_a_n_c_s___g_e_t___n_t_f___t.html", "struct_a_n_c_s___g_e_t___n_t_f___t" ],
    [ "ANCS_SOURCE_MSG_T", "struct_a_n_c_s___s_o_u_r_c_e___m_s_g___t.html", "struct_a_n_c_s___s_o_u_r_c_e___m_s_g___t" ],
    [ "BeanAncsClass", "class_bean_ancs_class.html", "class_bean_ancs_class" ],
    [ "BeanClass", "class_bean_class.html", "class_bean_class" ],
    [ "BeanHidClass", "class_bean_hid_class.html", "class_bean_hid_class" ],
    [ "BeanMidiClass", "class_bean_midi_class.html", "class_bean_midi_class" ],
    [ "BL_MSG_CMD_START_T", "struct_b_l___m_s_g___c_m_d___s_t_a_r_t___t.html", "struct_b_l___m_s_g___c_m_d___s_t_a_r_t___t" ],
    [ "BL_MSG_FW_BLOCK_T", "struct_b_l___m_s_g___f_w___b_l_o_c_k___t.html", "struct_b_l___m_s_g___f_w___b_l_o_c_k___t" ],
    [ "BL_MSG_STATUS_T", "struct_b_l___m_s_g___s_t_a_t_u_s___t.html", "struct_b_l___m_s_g___s_t_a_t_u_s___t" ],
    [ "BL_SKETCH_META_DATA_T", "struct_b_l___s_k_e_t_c_h___m_e_t_a___d_a_t_a___t.html", "struct_b_l___s_k_e_t_c_h___m_e_t_a___d_a_t_a___t" ],
    [ "BT_ADV_ONOFF_T", "struct_b_t___a_d_v___o_n_o_f_f___t.html", "struct_b_t___a_d_v___o_n_o_f_f___t" ],
    [ "BT_RADIOCONFIG_T", "struct_b_t___r_a_d_i_o_c_o_n_f_i_g___t.html", "struct_b_t___r_a_d_i_o_c_o_n_f_i_g___t" ],
    [ "BT_SCRATCH_T", "struct_b_t___s_c_r_a_t_c_h___t.html", "struct_b_t___s_c_r_a_t_c_h___t" ],
    [ "BT_SET_PIN_T", "struct_b_t___s_e_t___p_i_n___t.html", "struct_b_t___s_e_t___p_i_n___t" ],
    [ "BT_STATES_T", "struct_b_t___s_t_a_t_e_s___t.html", "struct_b_t___s_t_a_t_e_s___t" ],
    [ "CcReport", "struct_cc_report.html", "struct_cc_report" ],
    [ "ERROR_MSG_T", "struct_e_r_r_o_r___m_s_g___t.html", "struct_e_r_r_o_r___m_s_g___t" ],
    [ "HID_REPORT_T", "struct_h_i_d___r_e_p_o_r_t___t.html", "struct_h_i_d___r_e_p_o_r_t___t" ],
    [ "KeyReport", "struct_key_report.html", "struct_key_report" ],
    [ "LED_IND_SETTING_T", "struct_l_e_d___i_n_d___s_e_t_t_i_n_g___t.html", "struct_l_e_d___i_n_d___s_e_t_t_i_n_g___t" ],
    [ "LED_SETTING_T", "struct_l_e_d___s_e_t_t_i_n_g___t.html", "struct_l_e_d___s_e_t_t_i_n_g___t" ],
    [ "MouseReport", "struct_mouse_report.html", "struct_mouse_report" ],
    [ "OBSERVER_INFO_MESSAGE_T", "struct_o_b_s_e_r_v_e_r___i_n_f_o___m_e_s_s_a_g_e___t.html", "struct_o_b_s_e_r_v_e_r___i_n_f_o___m_e_s_s_a_g_e___t" ]
];